#!/bin/sh
project_prefix="KT"
branchname=$(git branch | grep ^* | sed 's/\* //g' | sed 's/feature\///g')
if [ "$branchname" = "master" ] || [ "$branchname" = "develop" ]
    then
    exit
fi
  
originalmessage=`cat $1`
  
if [[ $originalmessage == $branchname* ]] || [[ $originalmessage == "[$branchname]"* ]] || [[ $originalmessage == "[$project_prefix"* ]] || [[ $originalmessage == "$project_prefix"* ]] || [[ $originalmessage == "[NT]"* ]]
    then
    exit
fi
echo "[$branchname] $originalmessage" > $1